---
  - name: Clean up the Linux AWS Inventory - Managed inventory
    hosts: localhost
    connection: local
    gather_facts: no

    tasks:

    - name: End the play when there is nothing in the inventory
      when:
        delete_inventory_host is undefined
      ansible.builtin.meta: end_play

    - name: Get an AAP API Token and store it as new_token
      register: new_token
      ansible.builtin.uri:
        url: "https://{{ controller_url }}/api/v2/tokens/"
        method: POST
        user: "{{ controller_user }}"
        password: "{{ controller_passwd }}"
        validate_certs: no
        force_basic_auth: yes
        status_code: 201
        return_content: yes

    - name: Update the Linux AWS Managed Inventory
      awx.awx.host:
        controller_host: "https://{{ controller_url }}"
        controller_password: "{{ controller_passwd }}"
        controller_username: "{{ controller_user }}"
        controller_oauthtoken: "{{ new_token.json.token }}"
        name: "{{ delete_inventory_host }}"
        inventory: "Linux AWS Inventory - Managed"
        state: absent
        enabled: true
